// mockData.ts

import type { OrderDataType } from "../types";

export const ordersData: OrderDataType[] = [
    {
        key: 1,
        id: 1001,
        name: "Alisher Karimov",
        phone: "+998901234567",
        products: "iPhone 15 Pro",
        quantity: 2,
        isContacted: true,
    },
    {
        key: 2,
        id: 1002,
        name: "Malika Rahimova",
        phone: "+998931234567",
        products: "Samsung Galaxy S24",
        quantity: 1,
        isContacted: false,
    },
    {
        key: 3,
        id: 1003,
        name: "Jasur Toshmatov",
        phone: "+998911234567",
        products: "MacBook Air M2",
        quantity: 1,
        isContacted: true,
    },
    {
        key: 4,
        id: 1004,
        name: "Nodira Yusupova",
        phone: "+998941234567",
        products: "AirPods Pro",
        quantity: 3,
        isContacted: false,
    },
    {
        key: 5,
        id: 1005,
        name: "Sardor Mirzayev",
        phone: "+998951234567",
        products: "iPad Pro 12.9",
        quantity: 1,
        isContacted: true,
    },
    {
        key: 6,
        id: 1006,
        name: "Zulfiya Hasanova",
        phone: "+998961234567",
        products: "Sony WH-1000XM5",
        quantity: 2,
        isContacted: false,
    },
    {
        key: 7,
        id: 1007,
        name: "Bekzod Normatov",
        phone: "+998971234567",
        products: "Dell XPS 15",
        quantity: 1,
        isContacted: true,
    },
    {
        key: 8,
        id: 1008,
        name: "Shahnoza Ergasheva",
        phone: "+998981234567",
        products: "Apple Watch Series 9",
        quantity: 2,
        isContacted: true,
    },
    {
        key: 9,
        id: 1009,
        name: "Otabek Saidov",
        phone: "+998991234567",
        products: "Xiaomi 14 Ultra",
        quantity: 1,
        isContacted: false,
    },
    {
        key: 10,
        id: 1010,
        name: "Feruza Qodirova",
        phone: "+998901112233",
        products: 'LG OLED TV 55"',
        quantity: 1,
        isContacted: true,
    },
    {
        key: 11,
        id: 1011,
        name: "Ulugbek Xolmatov",
        phone: "+998912223344",
        products: "Canon EOS R50",
        quantity: 1,
        isContacted: false,
    },
    {
        key: 12,
        id: 1012,
        name: "Dilnoza Abdullayeva",
        phone: "+998923334455",
        products: "Samsung 4K Monitor",
        quantity: 2,
        isContacted: true,
    },
    {
        key: 13,
        id: 1013,
        name: "Sherzod Boymurodov",
        phone: "+998934445566",
        products: "Logitech MX Master 3",
        quantity: 4,
        isContacted: false,
    },
    {
        key: 14,
        id: 1014,
        name: "Maftuna Xasanova",
        phone: "+998945556677",
        products: "Huawei MatePad Pro",
        quantity: 1,
        isContacted: true,
    },
    {
        key: 15,
        id: 1015,
        name: "Doniyor Rajabov",
        phone: "+998956667788",
        products: "PlayStation 5",
        quantity: 1,
        isContacted: false,
    },
    {
        key: 16,
        id: 1016,
        name: "Kamola Tursunova",
        phone: "+998967778899",
        products: "Nintendo Switch OLED",
        quantity: 2,
        isContacted: true,
    },
    {
        key: 17,
        id: 1017,
        name: "Mansur Djalolov",
        phone: "+998978889900",
        products: "GoPro Hero 12",
        quantity: 3,
        isContacted: false,
    },
    {
        key: 18,
        id: 1018,
        name: "Barno Nazarova",
        phone: "+998989990011",
        products: "Kindle Paperwhite",
        quantity: 5,
        isContacted: true,
    },
    {
        key: 19,
        id: 1019,
        name: "Firdavs Usmonov",
        phone: "+998900001122",
        products: "DJI Mini 4 Pro",
        quantity: 1,
        isContacted: false,
    },
    {
        key: 20,
        id: 1020,
        name: "Gulnora Ismoilova",
        phone: "+998910002233",
        products: "Bose QuietComfort 45",
        quantity: 2,
        isContacted: true,
    },
];
